[versions]

agp = "8.12.3"
mavenPublish = "0.28.0"
metalava = "0.3.5"

# Kotlin
kotlin = "2.3.0"
dokka = "1.9.20"

# Compose
compose = "1.10.0"
compose-plugin = "1.10.0"
navigation = "2.9.1"

# AndroidX
androidx-activity = "1.12.2"
androidx-tracing = "1.3.0"

[libraries]

# Compose

compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-ui-testJunit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-testManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }

jetbrains-annotation = { module = "org.jetbrains.compose.annotation-internal:annotation", version.ref = "compose-plugin" }
jetbrains-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation" }

# AndroidX

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-tracing = { module = "androidx.tracing:tracing", version.ref = "androidx-tracing" }

# Test

androidx-test-core = "androidx.test:core:1.7.0"
androidx-test-rules = "androidx.test:rules:1.7.0"
androidx-test-runner = "androidx.test:runner:1.7.0"

# Dependencies of the included build-logic
android-pluginGradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-pluginGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
compose-compiler-pluginGradle = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
metalava-pluginGradle = { module = "me.tylerbwong.gradle.metalava:plugin", version.ref = "metalava" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
metalava = { id = "me.tylerbwong.gradle.metalava", version.ref = "metalava" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
